name: TechTrends - Package with Docker

on:
  push:
    branches:
        - main
        - develop
        - feature/*
        - hotfix/*
        - release/*
        - bugfix/*
        - support/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./project/techtrends
          push: true
          tags: techtrends:latest
          dockerfile: ./project/techtrends/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



